[tool.poetry]
name = "outfit-assistant"
version = "0.1.0"
description = ""
authors = ["IvanTykhonchuk <iv.tikhonchuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
